# compose file format version 
# (see https://docs.docker.com/compose/compose-file/) 
version: "3.7"

services:
# service name 	
  php:
#   build: location of the Dockerfile
    build: ./php
#   volumes: mappling local to container
    volumes: 
#	use cwd for website
        - ../../proj2php/jeffstickyphp/:/var/www/html
#	log to localhost (debugging only)
        - /var/log:/var/log
#   port forward 80 from container to 8700 host
    ports:
        - '8700:80'
#   environment variables
    environment:
        - XYZ="this is an example"
#   internal dependecies for order of ops
    depends_on:
        - db
# originally own, image, trying to use docker image
#  db:
#   build: location of the Dockerfile
#    build: ./mysql

# using pre built image
  db:
    image: mysql:latest
    environment:	  
     MYSQL_DATABASE: ${DB_DATABASE}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
        - "3306:3306"
